### ISSUE TITLE
[Question] Will it work on Windows?

### ISSUE THREAD

**Issue by Suleman-Elahi** [Tachi107/cloudflare-ddns#1]
Can it be used on Windows or can Windows binary be generated?

**Comment by Tachi107** [comment]
I haven't used Windows in a while, but I think it should work, as I don't use anything platform-specific. The only thing that I'm sure doesn't work properly is the installation, as I don't know where I should put the `config.yaml` file. 

Later today I'll set up a Windows CI that automatically uploads the compiled .exe, and I'll also test the program :)

**Comment by Tachi107** [comment]
Happy to let you know that Windows is finally supported!
You can compile the project from source by first [installing Meson](https://mesonbuild.com/SimpleStart.html#windows) and then running the commands `meson setup build` and `meson compile -C build`.
If you prefer, you can also download the latest snapshot from [AppVeyor](https://ci.appveyor.com/api/projects/Tachi107/cloudflare-ddns/artifacts/build/cloudflare-ddns.exe?branch=main&job=Environment:%20arch=x64,%20compiler=msvc2019)

**Comment by Suleman-Elahi** [comment]
I think it should be minor or maybe I am missing something but I am getting bad config file error.
![image](https://user-images.githubusercontent.com/24384996/113093620-e76f6700-920d-11eb-9cab-8252242014ab.png)

**Comment by Tachi107** [comment]
I think that you should add a space between the `:` and the values, since the config should be valid Yaml
